### ISSUE TITLE
RVIZ No fixed frame [world] Problem

### ISSUE THREAD

**Issue by almacitunaberk** [mit-acl/faster#6] opened 2020-06-27 15:37 UTC
First of all, I want to thank everyone who contributed to this beautiful project.

I use Ubuntu 18.04 and ros-melodic on my machine. 

I did everything in the right order. However, I am having an RVIZ problem:
It says that there is no Fixed Frame [world] does not exist. 
I would really appreciate if any one could help.

**Comment by jtorde** [comment] 2020-06-27 19:34
Hi @almacitunaberk! So I'm not able to reproduce this error on my machine, and I think this error shouldn't happen if all the commands are run in the right order... Could you take an screenshot of the TF tree? It should look like this:
![image](https://user-images.githubusercontent.com/36667775/85930557-656f9d80-b88b-11ea-9e8a-4c3cba654bdf.png)

This is how the default Rviz visualization should look like:

![image](https://user-images.githubusercontent.com/36667775/85930565-8637f300-b88b-11ea-9d49-1dfbebfed285.png)

Let me know how the TF looks in your case, to see if I can help further

Thanks!

**Comment by jtorde** [comment] 2020-07-04 00:49
Closing this for now, but feel free to open it again if you still have this problem

Thanks!

**Closed by jtorde** 2020-07-04 00:49 UTC
